### ISSUE TITLE
SEO Sitemap store code.

### ISSUE THREAD

**Issue by hungryRabbit** [Knectar/Magento-Store-Codes#4] opened 2015-04-17 14:34 UTC
Hi there. I wonder, can I remove default store code from XML Google sitemap ?

Ill already tried, to do this, with little core change - but no result.
Like this: ( in ```/www/app/code/core/Mage/Sitemap/Model/Sitemap.php``` )

```$websiteId = Mage::app()->getStore($storeId)->getWebsiteId(); 
$iDefaultStoreId = Mage::app()->getWebsite($websiteId)->getDefaultGroup()->getDefaultStoreId();
if (Mage::app()->getStore($iDefaultStoreId)->getStoreId() === $this->getStoreId()) {
	$baseUrl = Mage::app()->getStore($storeId)->getBaseUrl(Mage_Core_Model_Store::URL_TYPE_DIRECT_LINK);
} else {
	$baseUrl = Mage::app()->getStore($storeId)->getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK);
}```

If you have solution, please response:
undeadjey@gmail.com

And, thanks for your module - it's really helps)

**Comment by clockworkgeek** [comment] 2015-04-19 09:32
This is probably caused by something I [already knew](https://github.com/Knectar/Magento-Store-Codes/blob/379302f3cff5df5ced609597df09a7accea53f26/app/code/community/Knectar/Storecodes/Controller/Router.php#L47) but never had a reason to fix.

**Comment by clockworkgeek** [comment] 2015-04-19 19:26
Hi.

I started an experimental feature on a [new branch](https://github.com/Knectar/Magento-Store-Codes/tree/unique-domain) which should address this.  I would appreciate if you could try it first.

**Comment by clockworkgeek** [comment] 2016-03-20 16:03
I was able to recreate the issue and the aforementioned branch does help, so I merged it to master.

**Closed by clockworkgeek** 2016-03-20 16:03 UTC
